### ISSUE TITLE
automatic program termination

### ISSUE THREAD

**Issue by Jarvis559** [y9c/pseudoU-BIDseq#9]
Hi y9c!

I encountered two instances of automatic program termination. My command is `nohup apptainer run docker://y9ch/bidseq &` in the terminal. And I always keep the terminal on. The attatchment is the two log files.
[2024-01-11T111942.665433.snakemake.log](https://github.com/y9c/pseudoU-BIDseq/files/13910948/2024-01-11T111942.665433.snakemake.log)
[2024-01-12T003946.169422.snakemake.log](https://github.com/y9c/pseudoU-BIDseq/files/13910950/2024-01-12T003946.169422.snakemake.log)

I wonder what can I do, thank you so much!

**Comment by y9c** [comment]
Did you modified something else besides using the default command? The log file is not named as default.

**Comment by Jarvis559** [comment]
I just followed the instruction, after the configuration of data.yaml file, then the command `nohup apptainer run docker://y9ch/bidseq &` in the terminal. I will attach the data.yaml. 
![datayaml](https://github.com/y9c/pseudoU-BIDseq/assets/142398326/f12065c2-0d78-4bc1-9ff6-8f42d700a3b5)

**Comment by y9c** [comment]
If you keep the terminal open. You might not need the nohup command, since the pipeline can keep alive automatically.

If you prefer to use nohup. You have to use it correctly. It depends on how your system is configured, you can ask you system admin to learn more about it. Nohup do not mean not exit. Some old bash require user to add exit command after the nohup command is entered.

**Comment by Jarvis559** [comment]
ok, thanks a lot!

**Comment by y9c** [comment]
You are welcome. If you still have the same problem. Feel free to reopen this tissue.
